---
apiVersion: v1
kind: Pod
metadata:
  name: dind-pusher
  namespace: test
  labels:
    app: dind-pusher
spec:
  # Needs privileged for dockerd in DinD
  securityContext:
    runAsUser: 0
  containers:
    - name: dind
      image: docker:26-dind
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1000m"
      env:
        - name: DOCKER_TLS_CERTDIR
          value: "" # disable TLS in DinD
      args:
        - "--host=tcp://0.0.0.0:2375"
        - "--insecure-registry=registry.test.svc.cluster.local:5000"
      ports:
        - containerPort: 2375
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
    - name: docker-cli
      image: docker:26-cli
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      command: ["sh","-c","sleep 3650d"]
  volumes:
    - name: dind-storage
      emptyDir: {}
